{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "galaxy-bce.fullname" . }}-ingress
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "galaxy-bce.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "30"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "30"
spec:
  ingressClassName: nginx
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "galaxy-bce.fullname" . }}-svc
            port:
              number: {{ .Values.service.port }}
      - path: /dummy
        pathType: Prefix
        backend:
          service:
            name: {{ include "galaxy-bce.fullname" . }}-svc
            port:
              number: {{ .Values.service.port }}
{{- end }}
