{{- if .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "galaxy-bce.fullname" . }}-pdb
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "galaxy-bce.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "galaxy-bce.selectorLabels" . | nindent 6 }}
{{- end }}
