apiVersion: v1
kind: Service
metadata:
  name: {{ include "galaxy-bce.fullname" . }}-svc
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "galaxy-bce.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "galaxy-bce.selectorLabels" . | nindent 4 }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
      protocol: TCP
      name: http
