apiVersion: v1
kind: LimitRange
metadata:
  name: galaxy-bce-limits
  namespace: galaxy-bce-prod
  labels:
    app.kubernetes.io/name: galaxy-bce
spec:
  limits:
  - type: Container
    default:
      cpu: 250m
      memory: 512Mi
    defaultRequest:
      cpu: 50m
      memory: 128Mi
    min:
      cpu: 25m
      memory: 64Mi
    max:
      cpu: 500m
      memory: 1024Mi
  - type: Pod
    max:
      cpu: 2000m
      memory: 2048Mi
    min:
      cpu: 25m
      memory: 64Mi
