apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: galaxy-bce-pdb
  namespace: galaxy-bce-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: galaxy-bce
