apiVersion: v1
kind: Service
metadata:
  name: galaxy-bce-svc
  namespace: galaxy-bce-prod
  labels:
    app.kubernetes.io/name: galaxy-bce
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: galaxy-bce
  ports:
  - name: http
    port: 80
    targetPort: 5000
